services:
  mongo1:
    image: mongo:7
    container_name: mongo1
    ports:
      - 27018:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo2:
    image: mongo:7
    container_name: mongo2
    ports:
      - 27019:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:7
    container_name: mongo3
    ports:
      - 27020:27017
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo-setup:
    image: mongo:7
    container_name: mongo-setup
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      bash -c "
      sleep 30;
      echo 'rs.initiate({_id: \"rs0\", members: [{ _id: 0, host: \"mongo1:27017\" }, { _id: 1, host: \"mongo2:27017\" }, { _id: 2, host: \"mongo3:27017\" }]})' | mongosh --host mongo1:27017"

  restapi:
    image: nazonhou/gz-restapi:v1.0
    restart: no
    environment:
      PORT: ${PORT}
      DEFAULT_API_PREFIX: ${DEFAULT_API_PREFIX}
      NODE_ENV: ${NODE_ENV}
      MONGO_URL: ${MONGO_URL}
      MONGO_DATABASE: ${MONGO_DATABASE}
      CORS_ORIGINS: ${CORS_ORIGINS}
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - mongo1
      - mongo2
      - mongo3
      - mongo-setup
